GridMvc.Demo/Components/CustomersViewComponent.cs
using GridCore.Pagination;
using GridMvc.Demo.Models;
using GridMvc.Server;
using GridShared;
using GridShared.Utility;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace GridMvc.Demo.Components
{
    public class CustomersViewComponent : ViewComponent
    {
        private readonly NorthwindDbContext _context;

        public CustomersViewComponent(NorthwindDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync(string customersGridState = "")
        {
            IQueryCollection query = Request.Query;
            if (!string.IsNullOrWhiteSpace(customersGridState))
            {      
                try
                {
                    query = new QueryCollection(StringExtensions.GetQuery(customersGridState));
                }
                catch (Exception)
                {
                    // do nothing, gridState was not a valid state
                }
            }

            Action<IGridColumnCollection<Customer>> columns = c =>
            {
                /* Adding "CustomerID" column: */

                c.Add(o => o.CustomerID)
                    .Titled("ID");

                /* Adding "CompanyName" column: */
                c.Add(o => o.CompanyName)
                    .Titled("Company");

                /* Adding "ContactName" column: */
                c.Add(o => o.ContactName).Titled("ContactName").SetWidth(250);

                /* Adding "Address" column: */
                c.Add(o => o.Address)
                    .Titled("Address");

                /* Adding "City" column: */
                c.Add(o => o.City)
                    .Titled("City");

                /* Adding "PostalCode" column: */
                c.Add(o => o.PostalCode)
                    .Titled("Postal Code");

                /* Adding "Country" column: */
                c.Add(o => o.Country)
                    .Titled("Country");
            };

            var repository = new CustomersRepository(_context);
            var requestCulture = HttpContext.Features.Get<IRequestCultureFeature>();
            var locale = requestCulture.RequestCulture.UICulture.TwoLetterISOLanguageName;

            var server = new GridServer<Customer>(repository.GetAll(), query, false, "customersGrid",
                columns, 10, locale, GridPager.DefaultAjaxPagerViewName)
                .SetRowCssClasses(item => item.IsVip ? "success" : string.Empty)
                .Sortable()
                .Filterable()
                .WithMultipleFilters()
                .Searchable(true, false)
                .SetStriped(true)
                .ClearFiltersButton(true)
                .ChangePageSize(true)
                .WithGridItemsCount()
                .SetRemoveDiacritics<NorthwindDbContext>("RemoveDiacritics");
            var factory = Task<IViewComponentResult>.Factory;

            return await factory.StartNew(() => View(server.Grid));
        }
    }
}

GridMvc.Demo/Components/OrdersViewComponent.cs
using GridCore.Pagination;
using GridCore.Resources;
using GridMvc.Demo.Models;
using GridMvc.Demo.Resources;
using GridMvc.Server;
using GridShared;
using GridShared.Filtering;
using GridShared.Sorting;
using GridShared.Utility;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace GridMvc.Demo.Components
{
    public class OrdersViewComponent : ViewComponent
    {
        private readonly NorthwindDbContext _context;

        public OrdersViewComponent(NorthwindDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync(string ordersGridState = "")
        {
            IQueryCollection query = Request.Query;
            if (!string.IsNullOrWhiteSpace(ordersGridState))
            {      
                try
                {
                    query = new QueryCollection(StringExtensions.GetQuery(ordersGridState));
                }
                catch (Exception)
                {
                    // do nothing, gridState was not a valid state
                }
            }

            var requestCulture = HttpContext.Features.Get<IRequestCultureFeature>();
            var locale = requestCulture.RequestCulture.UICulture.TwoLetterISOLanguageName;
            SharedResource.Culture = requestCulture.RequestCulture.UICulture;

            var shippersRepository = new ShippersRepository(_context);
            var shipperList = shippersRepository.GetAll()
                .Select(s => new SelectItem(s.ShipperID.ToString(), s.CompanyName))
                .ToList();

            Action<IGridColumnCollection<Order>> columns = c =>
            {
                /* Adding not mapped column, that renders body, using inline Razor html helper */
                c.Add()
                    .Encoded(false)
                    .Sanitized(false)
                    .SetWidth(60)
                    .Css("hidden-xs") //hide on phones
                    .RenderValueAs(o => $"<b><a class='modal_link' href='javascript:void(0);' onclick='editOrder({o.OrderID})'>Edit</a></b>");

                /* Adding "OrderID" column: */

                c.Add(o => o.OrderID)
                    .Titled(SharedResource.Number)
                    .SetWidth(100)
                    .Sum(true);

                /* Adding "OrderDate" column: */
                c.Add(o => o.OrderDate, "OrderCustomDate")
                    .Titled(SharedResource.OrderCustomDate)
                    .SortInitialDirection(GridSortDirection.Descending)
                    .ThenSortByDescending(o => o.OrderID)
                    .SetCellCssClassesContraint(o => o.OrderDate.HasValue && o.OrderDate.Value >= DateTime.Parse("1997-01-01") ? "red" : "")
                    .Format("{0:yyyy-MM-dd}")
                    .SetWidth(110)
                    .Max(true).Min(true);

                c.Add(o => o.ShipVia)
                    .Titled("Via")
                    .SetWidth(250)
                    .RenderValueAs(o => o.Shipper?.CompanyName)
                    .SetListFilter(shipperList);

                /* Adding "CompanyName" column: */
                c.Add(o => o.Customer.CompanyName)
                    .Titled(SharedResource.CompanyName)
                    .SetWidth(250)
                    .SetInitialFilter(GridFilterType.StartsWith, "a")
                    .SetFilterWidgetType("CustomCompanyNameFilterWidget")
                    .Max(true).Min(true);

                /* Adding "ContactName" column: */
                c.Add(o => o.Customer.ContactName).Titled(SharedResource.ContactName).SetWidth(250)
                    .Max(true).Min(true);

                /* Adding "Freight" column: */
                c.Add(o => o.Freight)
                    .Titled(SharedResource.Freight)
                    .SetWidth(100)
                    .Format("{0:F}")
                    .Sum(true).Average(true).Max(true).Min(true)
                    .Calculate("Average 2", x => x.Get("Freight").SumValue.Number / x.Grid.ItemsCount)
                    .Calculate("Average 3", x => x.Get("Freight").SumValue.Number / x.Get("OrderID").SumValue.Number);


                /* Adding "Vip customer" column: */
                c.Add(o => o.Customer.IsVip)
                    .Titled(SharedResource.IsVip)
                    .SetWidth(80)
                    .Css("hidden-xs") //hide on phones
                    .RenderValueAs(o => o.Customer.IsVip ? Strings.BoolTrueLabel : Strings.BoolFalseLabel);
            };

            var repository = new OrdersRepository(_context);

            var server = new GridServer<Order>(repository.GetAll(), query, false, "ordersGrid",
                columns, 10, locale, GridPager.DefaultAjaxPagerViewName)
                .SetRowCssClasses(item => item.Customer.IsVip ? "success" : string.Empty)
                .Sortable()
                .Filterable()
                .WithMultipleFilters()
                .Searchable(true, false)
                .Groupable(true)
                .Selectable(true)
                .SetStriped(true)
                .ChangePageSize(true)
                .WithGridItemsCount()
                .SetRemoveDiacritics<NorthwindDbContext>("RemoveDiacritics");
            var factory = Task<IViewComponentResult>.Factory;

            return await factory.StartNew(() => View(server.Grid));
        }
    }
}

GridMvc.Demo/Views/Home/BlazorComponentView.cshtml
@using GridMvc.Demo.BlazorComponents

@{
    ViewBag.Title = "Blazor component";
}

<link rel="stylesheet" href="~/_content/GridBlazor/css/gridblazor.css" />

<div class="row">
    <div class="col-md-12">
        <p>Orders administration with a Blazor component in ASP.NET Core MVC</p>
        <p>
            This page demonstrates the possibilities of GridMvcCore. For more documentation, please
            see: <a href="https://github.com/gustavnavar/Grid.Blazor">https://github.com/gustavnavar/Grid.Blazor</a>
        </p>
    </div>
</div>

<div>
    @(await Html.RenderComponentAsync<OrdersComponent>(RenderMode.ServerPrerendered))
</div>

<script src="~/_content/GridBlazor/js/gridblazor.js"></script>
<script src="~/_framework/blazor.server.js" autostart="false"></script>

<script type="text/javascript">
    Blazor.start({
        configureSignalR: function (builder) {
            builder.withUrl("/_blazor");
        }
    });
</script>

GridMvc.Demo/Views/Home/Comparer.cshtml
@using GridCore
@addTagHelper *, GridMvc

@model ISGrid

@{
    ViewBag.Title = "Sorting Comparer";
}

<div class="row">
    <div class="col-md-12">
        <p>
            It's possible to use a custom comparer just in the case that all the  grid items are in memory.
        </p>
        <p>
            In this sample the first letter of the company name is removed and the rest of the word is sorted.
        </p>
        <p>
            See: <a href="https://github.com/gustavnavar/Grid.Blazor">https://github.com/gustavnavar/Grid.Blazor</a>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-9">
        <grid model="@Model" />
    </div>
    <div class="col-md-3">
        <h4>
            Order details
        </h4>
        <div id="order-content">
            <p class="muted">
                Select order to display detailed infomation
            </p>
        </div>
    </div>
</div>
<script>
    $(function () {
        pageGrids.ordersGrid.addFilterWidget(new CustomersFilterWidget());

        pageGrids.ordersGrid.onRowSelect(function (e) {
            $.get("/Home/GetOrder?id=" + e.row.OrderID, function (data) {
                if (data.status <= 0) {
                    alert(data.message);
                    return;
                }
                $("#order-content").html(data.content);
            });
        });
    });
</script>

GridMvc.Demo/Views/Home/Edit.cshtml
@using GridMvc.Demo.Models
@using System.Net;
@model Order

@{
    ViewBag.Title = "Edit Order";
     var error = TempData["error"];
     string returnUrl = (string)ViewData["returnUrl"];
     string gridState = (string)ViewData["gridState"];
     string altGridState = (string)ViewData["altGridState"];
     var requestCulture = Context.Features.Get<IRequestCultureFeature>();
}

<h1>@ViewBag.Title</h1>

@{
    if (error != null)
    {
        <p id="error" style="color:red;">@error.ToString()</p>
    }
    else
    {
        <p id="error" style="color:red;"></p>
    }
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.OrderID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-5">
            @Html.TextBoxFor(m => m.OrderID, htmlAttributes: new { @class = "form-control", @readonly = "readonly" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Customer, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-5">
            @Html.TextBoxFor(m => m.Customer.CompanyName, htmlAttributes: new { @class = "form-control", @readonly = "readonly" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OrderDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-5">
            @Html.TextBoxFor(m => m.OrderDate, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.OrderDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RequiredDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-5">
            @Html.TextBoxFor(m => m.RequiredDate, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.RequiredDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ShippedDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-5">
            @Html.TextBoxFor(m => m.ShippedDate, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ShippedDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ShipName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-5">
            @Html.TextBoxFor(m => m.ShipName, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ShipName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ShipAddress, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-5">
            @Html.TextBoxFor(m => m.ShipAddress, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ShipAddress, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ShipCity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-5">
            @Html.TextBoxFor(m => m.ShipCity, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ShipCity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ShipPostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-5">
            @Html.TextBoxFor(m => m.ShipPostalCode, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ShipPostalCode, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ShipRegion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-5">
            @Html.TextBoxFor(m => m.ShipRegion, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ShipRegion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ShipCountry, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-5">
            @Html.TextBoxFor(m => m.ShipCountry, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ShipCountry, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Freight, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-5">
            @Html.TextBoxFor(m => m.Freight, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Freight, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-5">
            @Html.HiddenFor(r => r.CustomerID)
            @Html.HiddenFor(r => r.EmployeeID)
            @Html.HiddenFor(r => r.ShipVia)
            @Html.Hidden("returnUrl", returnUrl)
            @Html.Hidden("gridState", gridState)
            @Html.Hidden("altGridState", altGridState)
            <input type="submit" value="Save" class="btn btn-default btn-md" />
            <a href="@WebUtility.UrlDecode(returnUrl)?gridState=@gridState&altGridState=@altGridState" class="btn btn-default btn-md">Back</a>
        </div>
    </div>
</div>
}

GridMvc.Demo/Views/Home/Images.cshtml
@using GridCore
@addTagHelper *, GridMvc

@model ISGrid

@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-md-12">
        <p>
            This page demonstrates the possibilities of GridMvcCore. For more documentation, please
            see: <a href="https://github.com/gustavnavar/Grid.Blazor">https://github.com/gustavnavar/Grid.Blazor</a>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <grid model="@Model" />
    </div>
</div>

GridMvc.Demo/Views/Home/Index.cshtml
@using GridCore
@addTagHelper *, GridMvc

@model ISGrid

@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-md-12">
        <p>
            This page demonstrates the possibilities of GridMvcCore. For more documentation, please
            see: <a href="https://github.com/gustavnavar/Grid.Blazor">https://github.com/gustavnavar/Grid.Blazor</a>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-9">
        <grid model="@Model" />
    </div>
    <div class="col-md-3">
        <h4>
            Order details
        </h4>
        <div id="order-content">
            <p class="muted">
                Select order to display detailed infomation
            </p>
        </div>
    </div>
</div>
<script>
    $(function () {
        pageGrids.ordersGrid.addFilterWidget(new CustomersFilterWidget());

        pageGrids.ordersGrid.onRowSelect(function (e) {
            $.get("/Home/GetOrder?id=" + e.row.OrderID, function (data) {
                if (data.status <= 0) {
                    alert(data.message);
                    return;
                }
                $("#order-content").html(data.content);
            });
        });
    });
</script>

GridMvc.Demo/Views/Home/MultipleGrids.cshtml
@{
    ViewBag.Title = "Home Page";
    string ordersGridState = (string)ViewData["ordersGridState"];
    string customersGridState = (string)ViewData["customersGridState"];
}

<script src="~/js/gridmvc-ajax.js" type="text/javascript"></script>
<script src="~/lib/URI.js/URI.js" type="text/javascript"></script>

<div class="row">
    <div class="col-md-12">
        <p>
            This page demonstrates the possibilities of GridMvcCore. For more documentation, please
            see: <a href="https://github.com/gustavnavar/Grid.Blazor">https://github.com/gustavnavar/Grid.Blazor</a>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <ul class="nav nav-tabs" id="nav-tab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="orders-tab" data-toggle="tab" href="#orders" role="tab" aria-controls="orders" aria-selected="true">
                    <label class="control-label">Orders</label>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="customers-tab" data-toggle="tab" href="#customers" role="tab" aria-controls="customers" aria-selected="false">
                    <label class="control-label">Customers</label>
                </a>
            </li>
        </ul>
        <div class="tab-content" id="nav-tabContent" style="margin-top:10px;">
            <div class="tab-pane fade show active" id="orders" role="tabpanel" aria-labelledby="orders-tab">
                <div class="row">
                    <div class="col-md-9">
                        @await Component.InvokeAsync("Orders", new { ordersGridState })
                    </div>
                    <div class="col-md-3">
                        <h4>
                            Order details
                        </h4>
                        <div id="order-content">
                            <p class="muted">
                                Select order to display detailed infomation
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="tab-pane fade" id="customers" role="tabpanel" aria-labelledby="customers-tab">
                <div class="row">
                    <div class="col-md-12">
                        @await Component.InvokeAsync("Customers", new { customersGridState })
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function gettoken() {
        var token = '@Html.AntiForgeryToken()';
        token = $(token).val();
        return token;
    }

    function editOrder(id) {
        var returnUrl = "/Home/MultipleGrids";
        var ordersGridState = pageGrids.ordersGrid.getState();
        var customersGridState = pageGrids.customersGrid.getState();
        window.location.replace("/Home/Edit/" + id + "?returnUrl=" + returnUrl + "&gridState=" + ordersGridState + "&altGridState=" + customersGridState);
    }

    $(function () {
        var token = gettoken();

        pageGrids.ordersGrid.addFilterWidget(new CustomersFilterWidget());

        pageGrids.ordersGrid.ajaxify({
            getPagedData: "/Home/GetOrdersGrid",
            token: token
        });

        pageGrids.ordersGrid.onRowSelect(function (e) {
            $.get("/Home/GetOrder?id=" + e.row.OrderID, function (data) {
                if (data.status <= 0) {
                    alert(data.message);
                    return;
                }
                $("#order-content").html(data.content);
            });
        });

        pageGrids.customersGrid.ajaxify({
            getPagedData: "/Home/GetCustomersGrid",
            token: token
        });
    });
</script>

GridMvc.Demo/Views/Home/RTL.cshtml
@using GridMvc
@using GridMvc.Demo.Models
@using GridShared
@model SGrid<Order>
@{
    ViewBag.Title = "Home Page";

    IEnumerable<SelectItem> shipperList = (IEnumerable<SelectItem>)ViewData["shipperList"];
}

<script src="~/js/gridmvc-ajax.js" type="text/javascript"></script>
<script src="~/lib/URI.js/URI.js" type="text/javascript"></script>

<div class="row">
    <div class="col-md-12">
        <p>
            This page demonstrates the possibilities of GridMvcCore. For more documentation, please
            see: <a href="https://github.com/gustavnavar/Grid.Blazor">https://github.com/gustavnavar/Grid.Blazor</a>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-9">
        @await Html.PartialAsync("_OrdersRTLGrid", Model)
    </div>
    <div class="col-md-3">
        <h4>
            Order details
        </h4>
        <div id="order-content">
            <p class="muted">
                Select order to display detailed infomation
            </p>
        </div>
    </div>
</div>

<script>
    $(function () {
        pageGrids.ordersGrid.addFilterWidget(new CustomersFilterWidget());

        pageGrids.ordersGrid.ajaxify({
            getPagedData: "/Home/GetOrdersRTLGridRows",
            getSubGridData: "/Home/GetSubgridRTL"
        });

        pageGrids.ordersGrid.onRowSelect(function (e) {
            $.get("/Home/GetOrder?id=" + e.row.OrderID, function (data) {
                if (data.status <= 0) {
                    alert(data.message);
                    return;
                }
                $("#order-content").html(data.content);
            });
        });
    });
</script>

GridMvc.Demo/Views/Home/Subgrid.cshtml
@using GridMvc
@using GridMvc.Demo.Models
@using GridShared
@model SGrid<Order>
@{
    ViewBag.Title = "Home Page";

    IEnumerable<SelectItem> shipperList = (IEnumerable<SelectItem>)ViewData["shipperList"];
}

<script src="~/js/gridmvc-ajax.js" type="text/javascript"></script>
<script src="~/lib/URI.js/URI.js" type="text/javascript"></script>

<div class="row">
    <div class="col-md-12">
        <p>
            This page demonstrates the possibilities of GridMvcCore. For more documentation, please
            see: <a href="https://github.com/gustavnavar/Grid.Blazor">https://github.com/gustavnavar/Grid.Blazor</a>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-9">
        @await Html.PartialAsync("_OrdersGrid", Model)
    </div>
    <div class="col-md-3">
        <h4>
            Order details
        </h4>
        <div id="order-content">
            <p class="muted">
                Select order to display detailed infomation
            </p>
        </div>
    </div>
</div>

<script>
    $(function () {
        pageGrids.ordersGrid.addFilterWidget(new CustomersFilterWidget());

        pageGrids.ordersGrid.ajaxify({
            getPagedData: "/Home/GetOrdersGridRows",
            getSubGridData: "/Home/GetSubgrid"
        });

        pageGrids.ordersGrid.onRowSelect(function (e) {
            $.get("/Home/GetOrder?id=" + e.row.OrderID, function (data) {
                if (data.status <= 0) {
                    alert(data.message);
                    return;
                }
                $("#order-content").html(data.content);
            });
        });

        pageGrids.ordersGrid.applyExtSortValues("Customer.CompanyName", 0, 1);
    });
</script>

GridMvc.Demo/Views/Home/_OrderInfo.cshtml
@model GridMvc.Demo.Models.Order

<dl>
    <dt>Order number:</dt>
    <dd>@Model.OrderID</dd>


    @if (Model.OrderDate.HasValue)
    {

        <dt>Order date:</dt>
        <dd>@Model.OrderDate.Value.ToString()</dd>

    }

    <dt>Freight:</dt>
    <dd>@Model.Freight</dd>

    <dt>
        Ship address:
    </dt>
    <dd>
        @Model.ShipPostalCode, @Model.ShipCity, @Model.ShipCity,
        @Model.ShipAddress
    </dd>

    <dt>
        Customer:
    </dt>
    <dd>@Model.Customer.CompanyName</dd>
</dl>